services:
  dev-db:
    container_name: dev-db
    image:
      docker.io/library/postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - mcnet
  test-db:
    container_name: test-db
    image: docker.io/library/postgres:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - mcnet
networks:
  mcnet:
