services:
  dev-db:
    image:
      postgres-13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - mcnet
  test-db:
    image: postgres-13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - mcnet
networks:
  mcnet:
